name: Update devenv.lock
on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:
jobs:
  update-devenv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install nixpkgs#devenv
      - name: Update devenv.lock
        run: devenv update
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update devenv.lock"
          title: "Update devenv.lock"
          branch: update-devenv-lock
          delete-branch: true
      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        run: gh pr merge --auto --squash update-devenv-lock
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
